import importlib.util
import os

import streamlit as st

SCRIPTS_DIR = os.path.dirname(os.path.abspath(__file__))


def _import_by_path(module_name, filename):
    spec = importlib.util.spec_from_file_location(module_name, os.path.join(SCRIPTS_DIR, filename))
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


rag_chain = _import_by_path("rag_chain", "07_rag_chain.py")


@st.cache_resource
def load_pipeline():
    embedder = rag_chain.get_embedding_model()
    index = rag_chain.get_pinecone_index()
    llm = rag_chain.get_llm()
    return embedder, index, llm


st.title("RAG Demo: Attention Is All You Need")
st.caption("Ask a question about the Transformer paper. Answers are generated by Claude, grounded in chunks retrieved from Pinecone.")

embedder, index, llm = load_pipeline()

question = st.text_input("Your question")

if st.button("Ask") and question:
    with st.spinner("Retrieving chunks and generating answer..."):
        answer, matches = rag_chain.answer_question(question, embedder, index, llm)

    st.subheader("Answer")
    st.write(answer)

    with st.expander("Sources used"):
        for m in matches:
            st.markdown(f"**Page {m['metadata']['page_label']}** (similarity score: {m['score']:.4f})")
            st.text(m["metadata"]["text"])
            st.divider()
